# Generated by Django 4.2.4 on 2023-08-23 09:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tutorial", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tutorialcomment",
            old_name="Tutorialcontent",
            new_name="tutorial",
        ),
        migrations.AlterField(
            model_name="tutorialcomment",
            name="comment",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="tutorialcontent",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
