# Generated by Django 4.2.4 on 2023-08-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorial", "0002_rename_tutorialcontent_tutorialcomment_tutorial_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorialcomment",
            name="comment",
            field=models.TextField(),
        ),
    ]
