# Generated by Django 4.2.4 on 2023-08-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorial", "0003_alter_tutorialcomment_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tutorial",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="tutorialcomment",
            options={"ordering": ["created"]},
        ),
        migrations.AlterModelOptions(
            name="tutorialcontent",
            options={"ordering": ["title"]},
        ),
        migrations.AddField(
            model_name="tagtutorial",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="tutorial",
            name="description",
            field=models.TextField(
                default="This is the description for the tutorial title"
            ),
            preserve_default=False,
        ),
    ]
