# Generated by Django 4.2.4 on 2023-08-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tutorial",
            "0004_alter_tutorial_options_alter_tutorialcomment_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tutorial",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
