# Generated by Django 4.2.4 on 2023-08-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutorial", "0005_alter_tutorial_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorialcontent",
            name="main_image",
            field=models.ImageField(null=True, upload_to="images/blogs"),
        ),
    ]
