# Generated by Django 4.2.4 on 2023-08-23 09:43

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="unpublish",
        ),
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="blogcomment",
            name="comment",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
