# Generated by Django 4.2.4 on 2023-08-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_remove_blog_unpublish_alter_blog_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcomment",
            name="comment",
            field=models.TextField(),
        ),
    ]
