# Generated by Django 4.2.4 on 2023-08-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_blog_options_alter_blogcomment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tagblog",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="tags",
            field=models.ManyToManyField(to="blog.tagblog"),
        ),
    ]
