# Generated by Django 4.2.4 on 2023-08-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_tagblog_description_alter_blog_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="views",
            field=models.IntegerField(default=0),
        ),
    ]
