# Generated by Django 4.2.4 on 2023-08-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_blog_main_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="tagblog",
            name="background_color",
            field=models.CharField(default="blue", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tagblog",
            name="border_color",
            field=models.CharField(default="red", max_length=255),
            preserve_default=False,
        ),
    ]
