# Generated by Django 4.2.4 on 2023-08-26 09:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_tagblog_background_color_tagblog_border_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tagblog",
            name="border_color",
        ),
    ]
