# Generated by Django 4.2.4 on 2023-08-29 19:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_remove_tagblog_border_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="blogcomment",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="tagblog",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
